#!/bin/bash
#
# The 'run' performs a simple test that verifies that image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-php:7.1}
VERSION=${VERSION-"7.1"}
S2I_ARGS=${S2I_ARGS:-""}

TEST_APPS=({phpinfo,laravel-unit-test-example})
VERSION_COMMAND="php -v"

extra_tests() {
  info '${app}: Test with PRESTISSIMO=TRUE'
  S2I_ARGS="-e PRESTISSIMO=TRUE" run_s2i_build ${app}
  CONTAINER_ARGS='-e PRESTISSIMO=TRUE' test_application
}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/s2i
