#!/bin/bash
#
# The 'run' performs a simple test that verifies that STI image.
# The main focus here is to excersise the STI scripts.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-php:7.1}
VERSION=${VERSION-"7.1"}
S2I_ARGS=${S2I_ARGS:-""}

TEST_APPS=({phpinfo,laravel-unit-test-example})
VERSION_COMMAND="php -v"
EXTRA_TESTS="info 'Testing PRESTISSIMO' && \
  CONTAINER_ARGS='-e PRESTISSIMO=true' test_application"

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/functions
