#!/bin/bash
source cgroup-limits

set -e
set -o pipefail

# Include hidden files
shopt -s dotglob

# Set the umask to be '002' so that any files/directories created from
# this point are group writable.
umask 002

# Calculate based on memory limits
if [ $MEMORY_LIMIT -gt 4096 ]; then
  php_memory_limit=512
  opcache_memory_limit=128
elif [ $MEMORY_LIMIT -gt 2048 ]; then
  php_memory_limit=368
  opcache_memory_limit=128
elif [ $MEMORY_LIMIT -gt 1024 ]; then
  php_memory_limit=256
  opcache_memory_limit=128
elif [ $MEMORY_LIMIT -gt 512 ]; then
  php_memory_limit=128
  opcache_memory_limit=128
else
  php_memory_limit=128
  opcache_memory_limit=64
fi

export PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-$php_memory_limit}
export OPCACHE_MEMORY_CONSUMPTION=${OPCACHE_MEMORY_CONSUMPTION:-$opcache_memory_limit}

max_workers=$((MEMORY_LIMIT/PHP_MEMORY_LIMIT))
[[ $max_workers -le 1 ]] && max_workers=2
[[ $max_workers -gt 64 ]] && max_workers=64
export WEB_CONCURRENCY=${WEB_CONCURRENCY:-$max_workers}

# Apache configuration
export DOCUMENTROOT=${DOCUMENTROOT:-/}

export PRESTISSIMO=${PRESTISSIMO:-"FALSE"}
export DEBUG=${DEBUG:-"FALSE"}

if [[ $DEBUG == "TRUE" ]]; then
  echo "-> DEBUG mode set to TRUE"
  export ERROR_REPORTING=${ERROR_REPORTING:-E_ALL & ~E_NOTICE}
  export DISPLAY_ERRORS=${DISPLAY_ERRORS:-ON}
  export DISPLAY_STARTUP_ERRORS=${DISPLAY_STARTUP_ERRORS:-ON}
  export TRACK_ERRORS=${TRACK_ERRORS:-ON}
  export HTML_ERRORS=${HTML_ERRORS:-ON}
  export OPCACHE_REVALIDATE_FREQ=${OPCACHE_REVALIDATE_FREQ:-0}
  export OPCACHE_VALIDATE_TIMESTAMPS${OPCACHE_VALIDATE_TIMESTAMPS:-1}
else
  export ERROR_REPORTING=${ERROR_REPORTING:-E_ALL & ~E_NOTICE}
  export DISPLAY_ERRORS=${DISPLAY_ERRORS:-OFF}
  export DISPLAY_STARTUP_ERRORS=${DISPLAY_STARTUP_ERRORS:-OFF}
  export TRACK_ERRORS=${TRACK_ERRORS:-OFF}
  export HTML_ERRORS=${HTML_ERRORS:-OFF}
  export OPCACHE_REVALIDATE_FREQ=${OPCACHE_REVALIDATE_FREQ:-2}
  export OPCACHE_VALIDATE_TIMESTAMPS${OPCACHE_VALIDATE_TIMESTAMPS:-0}
fi

export INCLUDE_PATH=${INCLUDE_PATH:-.:/opt/app-root/src}
export SESSION_PATH=${SESSION_PATH:-/tmp/sessions}
export SHORT_OPEN_TAG=${SHORT_OPEN_TAG:-OFF}
export PHPRC=${PHPRC:-/opt/app-root/etc/php.ini}
export PHP_INI_SCAN_DIR=${PHP_INI_SCAN_DIR:-"/usr/local/etc/php/conf.d/:/opt/app-root/"}

# Process templates
for file in $(find /opt/app-root/etc/ -name "*.template"); do
  envsubst < $file > ${file%%.template}
done
