#!/bin/bash -e

NAME="php"
DISPLAY_NAME="PHP"
TYPE="s2i"
VARIANTS="default,alpine"
VERSIONS="5.6,7.0,7.1"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
